FROM maven:amazoncorretto AS build
WORKDIR /app
COPY pom.xml ./
RUN mvn dependency:go-offline -B
COPY src ./src
RUN mvn clean package -DskipTests

FROM openjdk:26-jdk-slim-bookworm AS runtime
# GET /health curl -f http://127.0.0.1:port/health
RUN apt-get -y update; apt-get -y install curl
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 7700
CMD ["java", "-jar", "app.jar"]