name: ${APP_NAME}

services:
  postgres:
    image: postgres:17.5-alpine
    ports:
      - '${DB_PORT}:${DB_PORT}'
    networks:
      - network
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      DATABASE_URL: ${DATABASE_URL}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_DATABASE}']
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - db_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:2025-06-27-1
    ports:
      - '5050:80'
    networks:
      - network
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    healthcheck:
      test: ['CMD', 'wget', '-O', '-', 'http://localhost:80/misc/ping']
      interval: 10s
      timeout: 10s
      start_period: 160s
      retries: 3
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
        required: true

volumes:
  db_data:
  pgadmin_data:
networks:
  network:
    driver: bridge
