services:
  db:
    container_name: app-name_postgres-db
    image: postgres:16
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - app-network
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      DATABASE_URL: ${DATABASE_URL}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_DATABASE}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - app-name_postgres-db:/var/lib/postgresql/data
  db-manager:
    container_name: app-name_pgadmin
    image: dpage/pgadmin4:9.2.0
    ports:
      - "5050:80"
    networks:
      - app-network
    environment:
      PGADMIN_DEFAULT_EMAIL: rootemail@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    depends_on:
      - db
    volumes:
      - app-name_pgadmin:/var/lib/pgadmin

volumes:
  app-name_postgres-db:
  app-name_pgadmin:
networks:
  app-network:
    driver: bridge
